esphome:
  name: "sim900-module"
  libraries:
    - "PDUlib"

esp8266:
  board: d1_mini

external_components:
  - source: 
      type: git
      url: https://github.com/Dams51/esphome_sim900_custom
    components: [sim900]

uart:
  id: uart_bus        # Optional.
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX

sim900:
  id: gsm_module      # Optional.
  uart_id: uart_bus   # Optional.

sensor:
  - platform: sim900
    signal_reseau:
      name: "Sim900 Signal réseau"

binary_sensor:
  - platform: sim900
    etat_reseau:
      name: "Sim900 Etat réseau"

text_sensor:
  - platform: sim900
    etat_module:
      name: "Sim900 Etat du module"

gpio_switch:
  - platform: sim900
    power_key_pin:
      pin: D3


# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_enc_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A Fallback Hotspot"
    password: "xxxxxxxxxxx"
